
import java.time.LocalDate;
import com.bochkov.duty.planning.DutyPlan;
import com.bochkov.duty.planning.DutyAssigment;
import com.bochkov.duty.jpa.entity.Person;
import org.optaplanner.core.api.score.buildin.hardmediumsoft.HardMediumSoftScoreHolder;
import org.apache.commons.math3.stat.descriptive.SynchronizedSummaryStatistics;
import com.bochkov.duty.planning.service.PersonDutyCount;

import accumulate com.bochkov.duty.planning.service.functions.LoadBalanceByCountAccumulateFunction loadBalanceByCount;
import accumulate com.bochkov.duty.planning.service.functions.LoadBalanceAccumulateFunction loadBalance;

global  HardMediumSoftScoreHolder scoreHolder;

// A nurse can only work one shift per day, i.e. no two shift can be assigned to the same nurse on a day.
rule "нельзя дежурства без людей"

    when
        DutyAssigment(person==null)
    then
        scoreHolder.addMediumConstraintMatch(kcontext, -1);
end

rule "нельзя дежурства за подряд"

    when
        DutyAssigment(person!=null, $person:=person,$day:=day,$dutyType:=dutyType)
        DutyAssigment(person!=null, $person==person,$day==day.prev,$dutyType:=dutyType)
    then
        scoreHolder.addHardConstraintMatch(kcontext, -1);
end



/*rule "количество дежурств у людей"
salience 2
    when
        $person:Person() and
        $amount: Number() from accumulate(DutyAssigment( person==$person), count())
    then
        insertLogical(new PersonDutyCount($person,$amount));
end*/

rule "распределение дежурств у людей"

    when
       accumulate(
           DutyAssigment(person != null, $p : person);
           $total : loadBalanceByCount($p)
       )
    then
       // System.out.println("variance is " + $result);
        scoreHolder.addSoftConstraintMatch(kcontext, - (int) $total.getZeroDeviationSquaredSumRootMillis());
end

rule "распределение дежурств у людей по выходным"

    when
       accumulate(
           DutyAssigment(person != null , isWeekend(), $p : person);
           $total : loadBalanceByCount($p)
       )
    then
       // System.out.println("variance is " + $result);
        scoreHolder.addSoftConstraintMatch(kcontext, - (int) $total.getZeroDeviationSquaredSumRootMillis());
end
