###
GET http://localhost:8080/duty/rest
Accept: application/hal+json; charset=utf-8


###
POST http://localhost:8080/duty/rest/employees
Accept: application/hal+json; charset=utf-8
Content-Type: application/json; charset=utf-8

{
    "createdDate": null,
    "login": null,
    "post": "Техник",
    "firstName": "Ваня",
    "middleName": "Степанович",
    "lastName": "Пупкин",
    "roadToHomeTime": null,
    "new": true,
    "employeeGroup": "http://localhost:8080/duty/rest/employeeGroups/2",
    "shiftTypes": [
        "http://localhost:8080/duty/rest/shiftTypes/1",
        "http://localhost:8080/duty/rest/shiftTypes/2"
    ],
    "rang": "http://localhost:8080/duty/rest/rangs/22"
}

###
PUT http://localhost:8080/duty/rest/employees/1
Accept: application/json; charset=utf-8
Content-Type: application/json; charset=utf-8

{
  "createdDate": "2021-05-24T21:28:06.624",
  "login": "pupkin",
  "post": "Техник",
  "firstName": "Василий",
  "middleName": "Степанович",
  "lastName": "Пупкин",
  "roadToHomeTime": null,
  "new": false
}

####
GET http://localhost:8080/duty/rest/profile/employees
Accept: application/json; charset=utf-8
Content-Type: application/json; charset=utf-8

###
PUT http://localhost:8080/duty/rest/employees/1/rang
Content-Type: text/uri-list

http://localhost:8080/duty/rest/rangs/14


###
GET http://localhost:8080/duty/rest/employees/1
Accept: application/hal+json; charset=utf-8

